[package]
name = "mumsh"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
linefeed = "0.6"
libc = "0.2"
regex = "1"
nix = "0.25.0"
home = "0.5.3"
colored = "2.0.0"
termios = "0.3.3"
